### ISSUE TITLE
speaker observed a panic

### ISSUE THREAD

**Issue by cyclinder** [metallb/metallb#1175]
- Version of MetalLB:  v0.11.0
- Version of Kubernetes: v1.22
- Name and version of network addon: calico
- Whether you've configured kube-proxy for iptables or ipvs mode: iptables

1. I created a service by `kubectl apply -f `, the description of service is below shown:
```bash
[root@master deploy]# cat hello-svc1.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-service2
  labels:
    name: hello-service2
spec:
  type: ClusterIP
  ports:
  - port: 18081
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello
```
2. when I created the service, and I found the pod of speaker was CrashLoopBackOff. and I look its log, as shown below:
```
E0120 08:30:10.190897       1 runtime.go:78] Observed a panic: &errors.errorString{s:"unable to calculate an index entry for key \"submariner-k8s-broker/hello-service2-cluster-a\" on index \"ServiceName\": endpointSlice missing kubernetes.io/service-name label"} (unable to calculate an index entry for key "submariner-k8s-broker/hello-service2-cluster-a" on index "ServiceName": endpointSlice missing kubernetes.io/service-name label)
goroutine 31 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15a5c00, 0xc000160cf0)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x15a5c00, 0xc000160cf0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/cache.(*threadSafeMap).updateIndices(0xc0001a7b60, 0x0, 0x0, 0x176bf20, 0xc0002cdab0, 0xc00073c2d0, 0x2e)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/thread_safe_store.go:264 +0x4bd
k8s.io/client-go/tools/cache.(*threadSafeMap).Add(0xc0001a7b60, 0xc00073c2d0, 0x2e, 0x176bf20, 0xc0002cdab0)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/thread_safe_store.go:78 +0x145
k8s.io/client-go/tools/cache.(*cache).Add(0xc0000c7830, 0x176bf20, 0xc0002cdab0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/store.go:150 +0x105
k8s.io/client-go/tools/cache.newInformer.func1(0x15debc0, 0xc00000cf48, 0x1, 0xc00000cf48)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/controller.go:404 +0x15b
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000546280, 0xc0001a7bf0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/delta_fifo.go:507 +0x322
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0002ae3f0)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/controller.go:183 +0x42
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00057ff90)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00057ff90, 0x1946be0, 0xc0001a6000, 0xc000222001, 0xc0002b6000)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00057ff90, 0x3b9aca00, 0x0, 0xc00020c201, 0xc0002b6000)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/circleci/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc0002ae3f0, 0xc0002b6000)
	/home/circleci/go/pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/controller.go:154 +0x2e5
created by go.universe.tf/metallb/internal/k8s.(*Client).Run
	/home/circleci/project/internal/k8s/k8s.go:397 +0x375
``` 
Does anyone know what's going on here? Thanks!

**Comment by msherif1234** [comment]
I will repro and take a look

**Comment by fedepaol** [comment]
I believe the error is related to the fact that the endpoint slice is missing the label that is supposed to refer to the servicename:
`endpointSlice missing kubernetes.io/service-name label`

@cyclinder mind sharing the yaml of the endpoint slice resource?

**Comment by msherif1234** [comment]
yes that was the issue I used this yaml
```
---
# https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/
apiVersion: discovery.k8s.io/v1beta1
kind: EndpointSlice
metadata:
  name: endpoint-slices
  labels:
    kubernetes.io/service-name: service-and-endpointslice    
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.1.2.3"
    conditions:
      ready: true
    hostname: pod-1
    topology:
      kubernetes.io/hostname: node-1
      topology.kubernetes.io/zone: us-west2-a
 
---

# https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors
apiVersion: v1
kind: Service
metadata:
  name: service-and-endpointslice
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```

that works fine if I removed the following from endpointslice
```
labels:
    kubernetes.io/service-name: service-and-endpointslice    
```
speaker will crash with the same exact error 

`panic: unable to calculate an index entry for key "default/endpoint-slices" on index "ServiceName": endpointSlice missing kubernetes.io/service-name label [recovered]`

**Comment by cyclinder** [comment]
> 

sure :), the yaml of the endpoint slice resource is shown below:
```
[root@master ~]# kubectl get endpoints hello-service2 -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2022-01-20T03:28:29Z"
  creationTimestamp: "2022-01-20T03:28:29Z"
  labels:
    name: hello-service2
  name: hello-service2
  namespace: default
  resourceVersion: "9416229"
  uid: 73127308-440e-4402-9dca-4f46bfe74f71
subsets:
- addresses:
  - ip: 10.244.104.1
    nodeName: node2
    targetRef:
      kind: Pod
      name: hello-5796dc7bb9-6r2lp
      namespace: default
      resourceVersion: "7699782"
      uid: 906c9a06-f6b1-42a0-9144-06b643866c09
  - ip: 10.244.104.2
    nodeName: node2
    targetRef:
      kind: Pod
      name: hello-5796dc7bb9-cfkg2
      namespace: default
      resourceVersion: "7699794"
      uid: 930b9691-7f09-400e-ac7f-cab37b4652a4
  - ip: 10.244.104.4
    nodeName: node2
    targetRef:
      kind: Pod
      name: hello-5796dc7bb9-g5mzz
      namespace: default
      resourceVersion: "7699786"
      uid: f562d99c-13ea-4b32-a9c1-13ac759b5a1b
  ports:
  - port: 8080
    protocol: TCP
[root@master ~]# kubectl get endpoints hello-service1 -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2022-01-07T09:32:53Z"
  creationTimestamp: "2022-01-07T09:32:53Z"
  labels:
    name: hello-service
  name: hello-service1
  namespace: default
  resourceVersion: "7831035"
  uid: 118d367f-f6cf-41a4-bf21-b6f03b5c8d79
subsets:
- addresses:
  - ip: 10.244.104.1
    nodeName: node2
    targetRef:
      kind: Pod
      name: hello-5796dc7bb9-6r2lp
      namespace: default
      resourceVersion: "7699782"
      uid: 906c9a06-f6b1-42a0-9144-06b643866c09
  - ip: 10.244.104.2
    nodeName: node2
    targetRef:
      kind: Pod
      name: hello-5796dc7bb9-cfkg2
      namespace: default
      resourceVersion: "7699794"
      uid: 930b9691-7f09-400e-ac7f-cab37b4652a4
  - ip: 10.244.104.4
    nodeName: node2
    targetRef:
      kind: Pod
      name: hello-5796dc7bb9-g5mzz
      namespace: default
      resourceVersion: "7699786"
      uid: f562d99c-13ea-4b32-a9c1-13ac759b5a1b
  ports:
  - port: 8080
    protocol: TCP
```

**Comment by msherif1234** [comment]
the crash happens in sliceInforrmer goroutine that was set when the speaker started up to watch for sliceendpoints, I will see if I can make it fail gracefully with an eror w/o crash but at the end this is incorrect endpoint because of the missing yaml, so if u add the labels you will be good to go

**Comment by cyclinder** [comment]
> the crash happens in sliceInforrmer goroutine that was set when the speaker started up to watch for sliceendpoints, I will see if I can make it fail gracefully with an eror w/o crash but at the end this is incorrect endpoint because of the missing yaml, so if u add the labels you will be good to go

good! I totally agree with you, If there need fail gracefully with an eror w/o crash, Can I try it out?

**Comment by fedepaol** [comment]
So it looks like something submariner should address?

**Comment by cyclinder** [comment]
> 

yeah, submariner needs to address the problem of missing labels in the created endpointslice, and if metallb can make it fail gracefully with an error w/o crash, I guess it would be better, Can you agree it ?

**Comment by fedepaol** [comment]
Yep, the problem is, the error is caused by a callback to the informer code where we provide a key for the ep slices.
Not using the service name is as much as wrong and may cause other issues in metallb.
I am not sure we can handle it gracefully, but I did not dug deeply in the issue, so I may be wrong here

**Comment by cyclinder** [comment]
I see, Thanks @fedepaol

**Comment by msherif1234** [comment]
created issue here for referrence, https://github.com/kubernetes/client-go/issues/1053

**Comment by fedepaol** [comment]
@cyclinder would it make sense to file a submariner issue? I have no clue on how it works, but my understanding is, it clones the service and the endpoints somehow? Mind filing one?

**Comment by cyclinder** [comment]
hi @fedepaol，Sorry for delayed response! 

> @cyclinder would it make sense to file a submariner issue? I have no clue on how it works, but my understanding is, it clones the service and the endpoints somehow? Mind filing one?

yeah, I am going to submit an issue to submariner on this issue, I suspect that the endpointslice object created by submariner missing the label of `kubernetes.io/service-name`.

**Comment by Woytek-Polnik** [comment]
Could you share in which PR / release it was solved on MetalLB side? Seems that people see it working in MetalLB 13.X, and in 12.X it was not the case

**Comment by fedepaol** [comment]
In 0.13+ we changed the controller implementation, resolving the crash as a side effect of the new implementation (and I think by ignoring the ep slices belonging to a different cluster).
I am almost sure 0.12 and earlier still crash.

We never followed up the submariner issue because, as per this thread, it was not a metallb problem.

**Comment by Woytek-Polnik** [comment]
@fedepaol than you for confirming its 0.13+ with the 'fix'
I've reported it to RH & Openshift so they 'update' their fork
